### PR TITLE
Make it a package first and Executable second

### PR DESCRIPTION
**Pull request by dixonwille**
I have this project forked for a while and use it just for the package and not the executable. As I want this to be your project, I figured you may want the change. I did change the readme But I will be glad to revert/edit those changes if you would like this change. I did nothing but separate logic so it can either be ran through CLI or used by other packages.

### CODE REVIEW

**Comment by sanderhahn** [comment]
Thanks :) 👍

**Comment by dixonwille** [comment]
@sanderhahn don't forget to change ReadMe to point to your repository!

**Comment by dixonwille** [comment]
To install it is now

```bash
go get github.com/snaderhahn/gozip/gozip
```

as that is where the executable is. But to use as a package just use

```go
import "github.com/snaderhahn/gozip"
```

**Comment by sanderhahn** [comment]
Removed the command line tool and instead added some examples in the readme. Fixed the repository link in the readme :)

**Pull request merged**
